resources:
  cloud: gcp
  accelerators: T4:1  # Cheaper alternative for development/testing
  memory: 16+
  disk_size: 128
  use_spot: true
  ports: 8888
  any_of:
    - region: us-east4
    - region: us-central1
    - region: us-east5
    - region: us-west1
    - region: us-west4

file_mounts:
  ~/.gitconfig: ~/.gitconfig

workdir: .

setup: |
  echo -e "\n\n============   SKYPILOT SETUP: Byaldi Dev Setup   ============\n\n"

  # ========== Update & Install Essentials ==========
  sudo apt-get update -y
  sudo apt-get install -y --no-upgrade \
      curl \
      git \
      python3-dev \
      python3-pip \
      build-essential \
      poppler-utils

  # ========== Setup uv (Python package manager) ==========
  curl -LsSf https://astral.sh/uv/install.sh | sh
  export PATH="$HOME/.cargo/bin:$PATH"

  # ========== Python Environment Setup ==========
  cd ~/sky_workdir
  uv venv
  source .venv/bin/activate

  # ========== Install Byaldi and Dependencies ==========
  echo "Installing Byaldi with dependencies..."
  uv pip install -e "."
  uv pip install -e ".[dev]"
  
  # Install Jupyter and common packages
  uv pip install jupyter ipywidgets matplotlib seaborn pandas numpy
  
  echo "========== Package installation completed =========="

  # ========== Verify Installation ==========
  echo "========== Verifying Byaldi installation =========="
  python -c "
  import byaldi
  print(f'Byaldi version: {byaldi.__version__}')
  print('Byaldi imported successfully!')
  
  import torch
  print(f'PyTorch version: {torch.__version__}')
  print(f'CUDA available: {torch.cuda.is_available()}')
  if torch.cuda.is_available():
      print(f'CUDA version: {torch.version.cuda}')
      print(f'GPU: {torch.cuda.get_device_name(0)}')
  "
  
  # ========== Configure Jupyter ==========
  mkdir -p ~/.jupyter
  cat > ~/.jupyter/jupyter_notebook_config.py << EOF
  c.NotebookApp.ip = '0.0.0.0'
  c.NotebookApp.port = 8888
  c.NotebookApp.open_browser = False
  c.NotebookApp.allow_remote_access = True
  c.NotebookApp.token = ''
  c.NotebookApp.password = ''
  EOF

  # Auto-source virtual environment
  echo 'source ~/sky_workdir/.venv/bin/activate' >> ~/.bashrc

  echo -e "\n\n============   SKYPILOT SETUP: Byaldi dev setup completed!   ============\n\n"

run: |
  echo "Starting Jupyter notebook server for development..."
  cd ~/sky_workdir
  source .venv/bin/activate
  
  # Copy examples to a working directory
  mkdir -p ~/notebooks
  if [ -d "examples" ]; then
    cp -r examples/* ~/notebooks/
    echo "Examples copied to ~/notebooks/"
  fi
  
  # Start Jupyter
  jupyter notebook --notebook-dir=~/notebooks --allow-root
